apiVersion: integration/v1
kind: Step
name: run
version: 3
summary: Run
description: |
  This step performs a Bolt run.
icon:
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/bolt-step-run
schemas:
  spec:
    source: file
    file: spec.schema.json
examples:
- summary: Run a Task against a single target 
  content:
    apiVersion: v1 
    kind: Step
    name: bolt-run 
    image: relaysh/bolt-step-run
    spec:
      type: task
      name: !Parameter task_name
      targets:
      - !Parameter target_url
      credentials:
        id_rsa: !Secret id_rsa
      transport:
        type: ssh
        user: !Parameter user 
        privateKey: id_rsa