# described here: https://github.com/puppetlabs/relay-rfcs/blob/main/content/0006-integration-layout/rfc.md
apiVersion: integration/v1
kind: Step
name: run
version: 3
summary: Runs a Bolt task or plan
description: Performs a Bolt run.
icon:
build:
  apiVersion: build/v1
  kind: Docker
    #publish:
    #  repository: relaysh/bolt-step-run
schemas:
  outputs:
    source: file
    file: outputs.schema.json
  spec:
    source: file
    file: spec.schema.json
examples:
- summary: Run a Bolt Task against a single target
  content:
    apiVersion: v1
    kind: Step
    name: bolt-run
    image: relaysh/bolt-step-run
    spec:
      type: task
      name: ${parameters.taskName}
      targets:
      - ${parameters.targetUrl}
      credentials:
        sshKey: ${secrets.sshKey}
      transport:
        type: ssh
        user: ${parameters.user}
        privateKey: sshKey
